name: 🔮 Sync Mirror

on:
  workflow_dispatch:
    
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Gitee
        uses: jikkai/sync-gitee@main
        with:
          repository: dream-num/usip-example
          username: ${{ secrets.GITEE_USERNAME }}
          password: ${{ secrets.GITEE_PASSWORD }}
          tags: true
          branches: main