host: http://localhost:8090
server:
  port: 8090

database:
  driver: sqlite
  dsn: demo.db

redis:
  enabled: false
  addr: 127.0.0.1:6379

universer:
  host: http://localhost:8000

univer:
  sheetHost: /sheet

font: web/public/font/SourceHanSansCN-VF.ttf
