host: http://localhost:8080

database:
  driver: postgresql
  dsn: user=postgres password=postgres dbname=demo host=127.0.0.1 port=5432 sslmode=disable TimeZone=Asia/Shanghai

redis:
  addr: 127.0.0.1:6379

universer:
  host: http://localhost:8000

univer:
  docHost: http://localhost:3010/doc
  sheetHost: http://localhost:3010/sheet

font: web/public/font/SourceHanSansCN-VF.ttf